### ISSUE TITLE
User - Unnecessary Coupling

### ISSUE THREAD

**Issue by JordanHSmith** [mzhang9622/Group-Sprint-1-Bookazon#10]
https://github.com/mzhang9622/Group-Sprint-1-Bookazon/blob/92c5cfbbf2406fe7f4c2dac6e0cdaae62f31f6d8/src/User.java#L25

Cart object is instantiated when this should be passed into the User constructor as an argument.

**Comment by mzhang9622** [comment]
Additionally in this function, consider making a class for name and subscription to avoid data clumping and primitive obsession. Helps to reduce parameters by 1
