### ISSUE TITLE
Unused UpdatedQuantity in Cart.java

### ISSUE THREAD

**Issue by cyu25** [mzhang9622/Group-Sprint-1-Bookazon#30]
https://github.com/mzhang9622/Group-Sprint-1-Bookazon/blob/778522af2e1b96eed5a64a725716c7b324c17dfa/src/Cart.java#L18-L25

Currently UpdatedQuantity is not being used in any of the other files. Therefore, it is considered unnecessary. We either should delete this code or incorporate it to one of our created methods.

**Comment by JordanHSmith** [comment]
This code has been commented out, thereby solving this issue. A new issue has been opened to delete the edited code.
