### ISSUE TITLE
Bookazon.java - Too many parameters

### ISSUE THREAD

**Issue by mzhang9622** [mzhang9622/Group-Sprint-1-Bookazon#4]
https://github.com/mzhang9622/Group-Sprint-1-Bookazon/blob/92c5cfbbf2406fe7f4c2dac6e0cdaae62f31f6d8/src/Bookazon.java#L42-L47

Similar to the issue with primitive obsession, utilize a new class with getters and setters, where all we'd need is pass in one item that contains the attributes of the book for us to use.

Suggestion: either create new methods that take individual parameters. Or use a newly created class.

**Comment by mzhang9622** [comment]
Could possibly even be a duplicate code, considering the same getter and setter is done in Book.java

**Comment by cyu25** [comment]
Adding onto this thought, by utilizing a new class (e.g public class BookDetails), and then in updateBookDetails, pass BookDetails as a parameter, we can avoid **data clumps** that is currently being demonstrated.

**Comment by mzhang9622** [comment]
About that idea, it would work if we can change the main code, because currently in Bookazon.java we make a new book object within the addBook function, which I believe violates SOLID principles, but I'm not sure if we can change the main code.

**Comment by mzhang9622** [comment]
Duplicate code in the end. We decided to delete it.
