### ISSUE TITLE
unnecessary Code in Book.java

### ISSUE THREAD

**Issue by cyu25** [mzhang9622/Group-Sprint-1-Bookazon#6]
https://github.com/mzhang9622/Group-Sprint-1-Bookazon/blob/92c5cfbbf2406fe7f4c2dac6e0cdaae62f31f6d8/src/Book.java#L63-L78

In Book.java, there are a few methods that have been coded up but not used in any of the existing classes (see attached). Therefore, it has been proposed to do a code redesign where we either use the validity statements or completely remove them when checking the features of a book.

**Comment by mzhang9622** [comment]
Overlapped with another issue before, thus has been resolved.
